### ISSUE TITLE
pyramid_basemodel is incompatible with zope.sqlalchemy 1.2

### ISSUE THREAD

**Issue by fizyk** [fizyk/pyramid_basemodel#13]
https://github.com/zopefoundation/zope.sqlalchemy/blob/master/CHANGES.rst

That's due to 
```
To make things clearer we renamed the ZopeTransactionExtension class to ZopeTransactionEvents. Existing code using the 'register' version stays compatible.
```

**Comment by fizyk** [comment]
pr #14 seems to be fixing this issue

**Comment by fizyk** [comment]
@thruflo thanks for merging #14 with a fix. Any chance on releasing this fix to pypi?

Also, would you like any help plugging CI and possibly dependabot to automatically run tests against newer dependency versions?

**Comment by thruflo** [comment]
I'm conscious I'm not active with this any more -- would you be interested in taking over maintaining? There's https://github.com/thruflo/pyramid_basemodel and also https://github.com/thruflo/pyramid_simpleauth

**Comment by fizyk** [comment]
I would be interested, but just in the pyramid_basemodel, not the pyramid_simpleauth. Or not yet, since I already maintain an auth extension for pyramid (pyramid_fullauth).

There's a chance I'll use pyramid_basemodel at work, which will give me an opportunity to direct a bit of the effort to the pyramid_basemodel itself.

**Comment by thruflo** [comment]
OK, great.  I'm happy to transfer repo and I can add you on PyPI for the package?

On simpleauth, I'd also be happy to flag up in the readme that fullauth may be a better option if you're actively maintaining it?

**Comment by fizyk** [comment]
Hmmm.... You can flag up, with fullauth, link to https://trypyramid.com/extending-pyramid.html and call for a maintainer (in case someone would want to use simpleauth anyway).

My pypi user is https://pypi.org/user/fizyk/

**Comment by thruflo** [comment]
Thanks for taking this on :)
