### ISSUE TITLE
ImportError: cannot import name 'ZopeTransactionExtension' from 'zope.sqlalchemy'

### ISSUE THREAD

**Issue by marquicus** [fizyk/pyramid_basemodel#17]
It seem a documented issue for [zope.sqlalchemy](https://github.com/zopefoundation/zope.sqlalchemy/issues/37#issuecomment-543435638)

```
ImportError: cannot import name 'ZopeTransactionExtension' from 'zope.sqlalchemy' (/home/marp/.virtualenvs/sandbox/lib/python3.8/site-packages/zope.sqlalchemy-1.3-py3.8.egg/zope/sqlalchemy/__init__.py)
make: *** [Makefile:160: initialization] Error 1
```

**Comment by fizyk** [comment]
@marquicus I uploaded the new version with the code there's on master and the fix for newer zope.sqlalchemy ought to be there.

However, I still have to push the basemodel through CI to properly test it and as I see it, fix the readme there...
